variables:
  UnityVersion: Unity2018.4.26f1

jobs:
- job: UnityValidation
  timeoutInMinutes: 90
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.4.26f1
    - SDK_18362 -equals TRUE
  steps:
  - template: build.yml
  - template: test.yml
  - template: package.yml
  - template: end.yml